development:
  adapter: postgresql
  encoding: unicode
  database: apply-to-mimosa_development
  pool: 5
  timeout: 5000
  username: daboor
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: apply-to-mimosa_test
  pool: 5
  timeout: 5000
  username: daboor
  password:
